let desc_clothing ={
  "origin": [
    "[setCountry:#country#][setTitle:#title#][setPronouns:#pronoun#]#intro# #physicaldesc#"
  ],
  "intro":[
    "My name is #name#. I am known as #title#.",
    "Some call me #title#, but you may call me #name#.",
    "Fear not! #title#, also known as #name# is here!",
    "This one is #name#. I am also called #title#."
  ],

  "country":[
    "[country:China][name:#chineseFamilyName# #chineseGivenName#]", 
    "[country:Persia][name:#persianFamilyName# #persianGivenName#]"

  ],
//Can try and hook in with a meta-variable?
  "chineseGivenName":[
    "#chineseMaleName#"
  ],

  "persianGivenName":[
    "#persianMaleName#",
    "#persianFemaleName#"
  ],
  "title":[
    "#title1# #title2#"
  ],
  "title1":[
    "Jade",
    "Timely",
    "Black",
    "Heavenly",
    "Great",
    "Resourceful",
    "Dragon",
    "Fiery",
    "Double",
    "Little",
    "Striking",
    "Lord",
    "Flowery",
    "General",
    "Featherless",
    "Blue",
    "Gold",
    "Impatient",
    "Magic",
    "Red Haired",
    "Winged",
    "River",
    "Prodigal",
    "Resourceful",
    "Guardian",
    "Ugly",
    "Sacred",
    "Multicolored",
    "Divine",
    "Lonely",
    "Iron",
    "White Flower",
    "Fair Skinned",
    "Giant",
    "Demon",
    "Faceless",
    "Flea",
    "Goddess",
    "Golden Haired"
  ],

  "title2":[
    "Rain",
    "Star",
    "Clouds",
    "Blade",
    "Head",
    "Thunderbolt",
    "Whirlwind",
    "Hawk",
    "Beautiful Beard",
    "Monk",
    "Arrow",
    "Beast",
    "Lancer",
    "Dervish",
    "Vanguard",
    "Traveller",
    "Devil",
    "Tiger",
    "Dragon",
    "Brother",
    "Wanderer",
    "Strategist",
    "Consort",
    "Vision",
    "Holy Fire",
    "Scholar",
    "Clerk",
    "Mathematician",
    "Physician",
    "Count",
    "Sage",
    "Craftsman",
    "Deity",
    "Ape",
    "Turtle",
    "Fan",
    "Whistle",
    "Demon",
    "Lightning",
    "Road",
    "Hound",
    "Ox"

  ],
  "physicaldesc": [
    "#pronounThey.capitalize# #look.s# to be #quality#, and seem to be wearing #clothingadj.a# #setTorsoClothing#",
    "#pronounThey.capitalize# has #quality.a# look in #pronounTheir# eye. #pronounThey.capitalize# is wearing #clothingadj.a# #setTorsoClothing#"
  ],

  "look":[
    "look",
    "seem",
    "appear"
  ],
  "pronoun": [
    "[pronounThey:he][pronounTheir:his][setTorsoClothing:#heTorsoClothing#]",
    "[pronounThey:she][pronounTheir:her][setTorsoClothing:#sheTorsoClothing#]",
    "[pronounThey:they][pronounTheir:their][setTorsoClothing:#theyTorsoClothing#]"
  ],
  "quality": [
    "worn-out",
    "brave","willing","determined",
    "unwilling","reluctant",
    "rational","logical",
    "obedient",
    "caring","healing",
    "dynamic","changeable","mercurial","unpredictable",
    "weak","craven","fearful",
    "opinionated","cranky","resolute",
    "educating","guiding","helpful",
    "mystical","mysterious",
    "expositional","revealing",
    "confusing","egocentric","misleading","clever","manipulative",
    "thoughtless","silly","amusing",
    "innocent","naive","simple","straightforward","credulous","endearing",
    "reflecting",
    "quiet","secretive",
    "curious",
    "dedicated","driven",
    "fair","unbiased","patient",
    "thorough","crafty",
    "final","morbid","dark",
    "giving","generous","charitable","patronizing",
    "incredible",
    "wishful","ambitious",
    "dominating","demanding","angry","egocentric","dedicated",
    "alluring","deceitful"

  ],
  "clothingadj": [
    "torn", 
    "well-made",
    "luxurious",
    "simple",
    "ornarte",
    "elegant", 
    "linen", 
    "hemp", 
    "wool", 
    "silk",
    "fur",
    "brocade",
    "cotton",
    "quilted",
    "felt",
    "camel's hair",
    "lambskin",
    "velvet",
    "leather",
    "satin",
    "cashmere",
    "cloth",
    "gauze",
    "hemp",
    "khādī",
    "muslin",
    ""

  ],
  "heTorsoClothing": [
    "shirt",
    "doublet",
    "robe",
    "cioppa",
    "hanfu pao",
    "shenyi",
    "jeliqa",
    "vest",
    "waistcoat",
    "jobba",
    "kaftan",
    "kel'at",
    "coat",
    "jacket",
    "pustin",
    "reda",
    "arakqloq",
    "qamis",
    "xuandan",
    "yuanlingshan",
    "lanshan"
  ],
  "sheTorsoClothing": [
    "blouse",
    "gown",
    "long gown",
    "chemise",
    "cotehardie",
    "houppelande",
    "overgown",
    "hanfu qun",
    "pien fu",
    "sheni",
    "cador"
  ],
  "theyTorsoClothing": [
    "#heTorsoClothing#",
    "#sheTorsoClothing#"
  ],
//Taken from http://www.peiraeuspubliclibrary.com/names/medievalnames/medievalchina.html
  "chineseFamilyName":[
    "Ban",
    "Chang",
    "Chen",
    "Chu",
    "Dong",
    "Dou",
    "Fa",
    "Gou",
    "Huo",
    "Jian",
    "Li",
    "Liang",
    "Liu",
    "Lu",
    "Ma",
    "Meng",
    "Shang",
    "Xuan",
    "Wang",
    "Wei",
    "Wu",
    "Xiang",
    "Yin",
    "Zhao",
    "Zhuang",
    "Zuan"
  ],

  "chineseMaleName":[
    "Ao",
    "Bang",
    "Buwei",
    "Changdong",
    "Chao",
    "Chai",
    "Fuling",
    "Gao",
    "Guang",
    "Han",
    "He",
    "Hu Hai",
    "Jizi",
    "Ju",
    "Kang",
    "Long",
    "Lun",
    "Mang",
    "Qi",
    "Qian",
    "Qing",
    "She",
    "Sheng",
    "Shi",
    "Si",
    "Taizong",
    "Tian",
    "Wan",
    "Xian",
    "Xie",
    "Xin",
    "Xing",
    "Yang",
    "Yide",
    "Ying",
    "Yu",
    "Yuan",
    "Yun",
    "Zang",
    "Zhanghaui",
    "Zhao",
    "Zheng",
    "Zhou",
    "Ziying"
  ],

//From sources from https://s-gabriel.org/names/islamic.shtml

  "persianFemaleName": [
    "Bakht",
    "Bakht Dawlat",
    "Bakht Nigâr",
    "Dawlat",
    "Dawlat Bakht",
    "Dil",
    "Dil Dâr",
    "Dil Khûsh",
    "Dil Shâd",
    "Durr",
    "Fâkhire",
    "Firuz Bakht",
    "Firuze",
    "Gawhar",
    "Gawhar Shâd",
    "Gul",
    "Gul Badan",
    "Gul Bîkî",
    "Gul Nâr",
    "Gul Rang",
    "Gul Rukh",
    "Gul Shâd",
    "Husn Nigâr",
    "Jân",
    "La'l",
    "Mihr Bânû",
    "Mihr Khush",
    "Mihr Nigâr",
    "Nâr Gul",
    "Nigâr",
    "Nurûz",
    "Pîrûz",
    "Shâd Bakht",
    "Shâd Bânû",
    "Shahr Bânû",
    "Shîrîn"
  ],

  "persianMaleName": [
    "`Abd al-Khâliq",
    "`Abdullâh",
    "Abû Nasr",
    "`Alî",
    "`Ârif",
    "Hasan",
    "Khalîl",
    "Kulâl",
    "Mahmûd",
    "Muhammad",
    "Qutham",
    "`Ubaydullâh",
    "Ya`qûb",
    "Yûsuf"
  ],
  "persianFamilyName":[
    "Ahrâr",
    "Anjîr Faghnawî",
    "Attar",
    "Charkhî",
    "Ghujdawânî",
    "Hamadânî",
    "Isfahânî",
    "Kâshgharî",
    "Khâmûsh",
    "Naqshband",
    "Pârsâ",
    "Rîwgirawî",
    "Samâsiyî"
  ]
}
