let appearance ={
  "origin":["#line#"],
  "line":["#appearance.a# #person# #wearing# #color.a# #outerwear#"],
  "appearance":[ "angered", "ill", "angry", "intelligent", "mean", "cruel", "moody", "displaced", "sad", "dumb", "excited", "sick", "grumpy", "stupefied", "happy", "tired", "large", "muscular", "attractive", "painted", "petite", "blond", "blue-eyed", "polished", "brown-eyed", "rosy", "brunette", "scarred", "short", "cute", "small", "tall", "tattooed", "thick", "heavy", "tiny", "wiry"],
  "person":["man", "woman", "child", "figure", "person", "traveler", "adventurer", "character", "individual"],
  "wearing":["clothed in", "enveloped by", "swathed in", "wearing", "donning", "dressed in", "sporting"],
  "color": [ "white", "silver", "grey", "black", "navy", "blue", "cerulean", "sky blue", "turquoise", "blue-green", "azure", "teal", "cyan", "green", "chartreuse", "olive", "yellow", "gold", "amber", "orange", "brown", "orange-red", "red", "maroon", "rose", "red-violet", "pink", "magenta", "purple", "blue-violet", "indigo", "violet", "peach", "apricot", "ochre", "plum"],
  "outerwear" : [ "abaya", "anorak", "apron", "blazer", "cagoule", "cloak", "coat", "duffle coat", "duster", "frock coat", "gilet", "greatcoat", "hoodie", "jacket", "leather jacket", "matchcoat", "mess jacket", "mino", "opera coat", "overcoat", "pea coat", "poncho", "parka", "raincoat", "rain pants", "redingote", "robe", "shawl", "shrug", "ski suit", "sport coat", "top coat", "trench coat", "vest", "waistcoat", "windbreaker"]
  }
  
// @lee3206 (forked from intro_character.js)
let intro_character = {
  "origin":[
  //First person narration, each intro starts with:
  //This is my story. I first...
  //I approached the caravan looking like #line#. I then revealed myself by #verbSay# #intro# #physicaldesc#
  "[setTitle:#title#][setPronouns:#pronoun#] This is my story. I started to travel because #fullReason#. I first approached the caravan looking like #line#. I then revealed myself by #verbSaying#, \"#intro#\" #physicaldesc#.",
  "[setTitle:#title#][setPronouns:#pronoun#] This is my story. I began to travel because #fullReason#. I first hid, only revealing myself to the caravan from afar. When I approached, I said \"#intro#\" #physicaldesc#.",
  "[setTitle:#title#][setPronouns:#pronoun#] This is my story. I initiated my journey because #fullReason#. I first saw the caravan in the distance, and ran to approach. I looked like #line#, and #verbSay.ed#, \"#intro#\" #physicaldesc#."
  ],

  "verbSaying": [
  "saying",
  "shouting",
  "whispering",
  "crying",
  "declaring",
  "announcing",
  "revealing",
  "stating",
  "voicing"
  ],
  "verbSay":[
  "say",
  "shout",
  "whisper",
  "cry",
  "declare",
  "announce",
  "reveal",
  "state",
  "voice"

  ]
}
let reason_travel = {
  "origin":[
  "[setReason:#fullReason#] #fullReason#"
  ],

  "fullReason":[
  "I am #reasonIng#",
  "#reasonIWas#"
  ],
  "reasonIng": [
  "<motive:fortune>searching for my fortune",
  "<motive:exile>exiled by an enemy",
  "<motive: lost>shipwrecked and finding my way home",
  "<motive: quest>on a routine trading journey",
  "<motive: quest>on a religious quest",
  "<motive: revenge>seeking revenge against the bandit king",
  "<motive: improvement>trying to overthrow the despot",
  "<motive: improvement>trying to prove my bravery",
  "<motive: revenge>getting revenge against my nemesis",
  "<motive: rescue>rescueing my #lovedOne#",
  "<motive: fortune>going home to claim my inheritance",
  "<motive: lost>finding my lost homeland",
  "<motive: knowledge>looking for historical records",
  "<motive: hide>in disguise to hide from my parents",
  "<motive: achievement>going to capture every animal",
  "<motive: achievement>planning to steal the greatest treasure",
  "<motive: reunite>trying to be reunited with my lover",
  "<motive: improvement>freeing my people",
  "<motive: achievement>making maps of the silk road",
  "<motive: novelty>trying to see new things",
  "<motive: novelty>traveling to have an adventure",
  "<motive: improvement>becoming a great artist",
  "<motive: improvement>learning from a skilled master",
  "<motive: quest>on a ritual journey",
  "<motive: quest>traveling as part of my religious devotion",
  "<motive: knowledge>seeking forbidden knowledge",
  "<motive: improvement>traveling to become the best #trade#",
  "<motive: improvement>mastering the sword",
  "<motive: improvement>writing a novel",
  "<motive: fortune>traveling to become wealthy by selling my cargo",
  "<motive: quest>escorting a #promisedOne# to their new family",
  "<motive: improvement>seeking to win the tournaments of my martial art",
  "<motive: fortune>collecting debts",
  "<motive: quest>travelling to fulfill my destiny",
  "<motive: rescue>searching a cure for my #lovedOne# illness",
  "<motive: achievement>trying to become famous",
  "<motive: improvement>planning to claim the throne that is rightfully mine",
  "<motive: rescue>searching for my lost twin",
  ],

  "reasonIWas":[
  "I accidentally killed a vile man and now I am a wanted fugitive from #town#",
  "I was disgraced as a monk and kicked out of the temple near #town#",
  "I was too harsh to the wrong person during training, and a highborn noble took offence",
  "an opposing noble stole my attractive partner and maneuvered me out of my house in #town#",
  "I was robbed when transporting sensitive materials and unfairly blamed for the loss",
  "I was branded and exiled from my home in #town#",
  "I've gambled away everything and I had to leave #town#",
  "my partner was extorting me, and during an argument I accidentally killed them. I fled #town# to avoid punishment",
  "I was having an affair and fled #town# to escape their partner's wrath",
  "I was so blackout drunk that I think I killed someone. I fled #town# in a haze in the night",
  "I was tricked into leaving my #town#. I later found my partner was having an affair with #char#, and I decided to leave"
  ],

  "promisedOne":[
  "bride",
  "groom",
  "promised partner",
  "loved one",
  "destined spouse",
  "engaged partner"

  ],

  "lovedOne":[
  "son",
  "daughter",
  "child",
  "father",
  "mother",
  "parent",
  "relative",
  "cousin",
  "spouse"
  ],

  "trade":[
  "chef",
  "merchant",
  "smith",
  "silver smith",
  "musician",
  "botanist"
  ]
   
}
let desc_clothing ={
  "myStory": [
    "[setTitle:#title#][setPronouns:#pronoun#]#intro# #physicaldesc#."
  ],
  "intro":[
    "My name is #name#. I am known as #title#.",
    "Some call me #title#, but you may call me #name#.",
    "Fear not! #title#, also known as #name# is here!",
    "This one is #name#. I am also called #title#.",
    "My legend proceeds me even here! I am #title#, named #name#.",
    "I doubt you have heard of me. I am #name#, sometimes called #title#.",
  ],
//Stopped for 11/30. Removed Indian family names for current
  "maleCountry":[
    "[country:China][name:#chineseFamilyName# #chineseMaleName#]", 
    "[country:Persia][name:#persianFamilyName# #persianMaleName#]",
    "[country:Byzantine][name:#byzantineMaleName# #byzantineFamilyName#]",
    "[country:Arabic][name:#arabicMaleSet#]",
    //According to SCA website, no real deleniation between male/female, so this should just work
    "[country:Mongolia][name:#mongolianName#]",
    "[country:India][name:#indianMaleName#]",
   // "[country:Iran][name:#iranianFamilyName# #iranianGivenName#]"

  ],

  "femaleCountry":[
    "[country:China][name:#chineseFamilyName# #chineseFemaleName#]", 
    "[country:Persia][name:#persianFamilyName# #persianFemaleName#]",
    "[country:Byzantine][name:#byzantineFemaleName# #byzantineFamilyName#]",
    "[country:Arabic][name:#arabicFemaleSet#]",
    "[country:Mongolia][name:#mongolianName#]",
    "[country:India][name:#indianFemaleName#]"
  ],

  "gnCountry":[
    "[country:China][name:#chineseFamilyName# #chineseGivenName#]", 
    "[country:Persia][name:#persianFamilyName# #persianGivenName#]",
    "[country:Byzantine][name:#byzantineGivenName# #byzantineFamilyName#]",
    "[country:Arabic][name:#arabicGivenName#]",
    "[country:Mongolia][name:#mongolianName#]",
    "[country:India][name:#indianGivenName#]"
  ],

  "chineseGivenName":[
    "#chineseMaleName#"
  ],

  "persianGivenName":[
    "#persianMaleName#",
    "#persianFemaleName#"
  ],

  "byzantineGivenName":[
    "#byzantineMaleName#",
    "#byzantineFemaleName#"
  ],

  "indianGivenName":[
    "#indianMaleName#",
    "#indianFemaleName#"
  ],

  "arabicGivenName":[
  //"ibm" is son of, "bint" is daughter of
  //According to the SCA website I drew these from, there is not really a historic practice of
  //including the name of the mother. I'd like to include that since we not cleaving to pure history.
    "#arabicMaleName# ibn #arabicFemaleName#",
    "#arabicMaleName# ibn #arabicMaleName#",
    "#arabicFemaleName# bint #arabicFemaleName#",
    "#arabicFemaleName# bint #arabicMaleName#"
  ],

  "arabicMaleSet":[
    "#arabicMaleName# ibn #arabicFemaleName#",
    "#arabicMaleName# ibn #arabicMaleName#"
  ],

  "arabicFemaleSet":[
    "#arabicFemaleName# bint #arabicFemaleName#",
    "#arabicFemaleName# bint #arabicMaleName#"

  ],

  "title":[
    "#title1# #title2#"
  ],
  "title1":[
    "Jade",
    "Timely",
    "Black",
    "Heavenly",
    "Great",
    "Resourceful",
    "Dragon",
    "Fiery",
    "Double",
    "Little",
    "Striking",
    "Lord",
    "Flowery",
    "General",
    "Featherless",
    "Blue",
    "Gold",
    "Impatient",
    "Magic",
    "Red Haired",
    "Winged",
    "River",
    "Prodigal",
    "Resourceful",
    "Guardian",
    "Ugly",
    "Sacred",
    "Multicolored",
    "Divine",
    "Lonely",
    "Iron",
    "White Flower",
    "Fair Skinned",
    "Giant",
    "Demon",
    "Faceless",
    "Flea",
    "Goddess",
    "Golden Haired",
    "Black Haired"
  ],

  "title2":[
    "Rain",
    "Star",
    "Cloud",
    "Blade",
    "Head",
    "Thunderbolt",
    "Whirlwind",
    "Hawk",
    "Beautiful Beard",
    "Monk",
    "Arrow",
    "Beast",
    "Lancer",
    "Dervish",
    "Vanguard",
    "Traveller",
    "Devil",
    "Tiger",
    "Dragon",
    "Brother",
    "Wanderer",
    "Strategist",
    "Consort",
    "Vision",
    "Holy Fire",
    "Scholar",
    "Clerk",
    "Mathematician",
    "Physician",
    "Count",
    "Sage",
    "Crafter",
    "Musician",
    "Deity",
    "Ape",
    "Turtle",
    "Fan",
    "Whistle",
    "Demon",
    "Lightning",
    "Road",
    "Hound",
    "Ox",
    "Lily",
    "Child",
    "Sibling",
    "Deva",
    "Dijin",
    "Hare",
    "Snake"

  ],
  "physicaldesc": [
    "I #look.ed# to be #quality#, and was wearing #clothingadj.a# #setTorsoClothing#",
    "I had #quality.a# look in my eye. I was wearing #clothingadj.a# #setTorsoClothing#"
  ],

  "look":[
    "look",
    "seem",
    "appear"
  ],
  "pronoun": [
    "[pronounThey:he][pronounTheir:his][setTorsoClothing:#heTorsoClothing#][setCountry:#maleCountry#]",
    "[pronounThey:she][pronounTheir:her][setTorsoClothing:#sheTorsoClothing#][setCountry:#femaleCountry#]",
    "[pronounThey:they][pronounTheir:their][setTorsoClothing:#theyTorsoClothing#][setCountry:#gnCountry#]"
  ],
  "quality": [
    "worn-out",
    "brave","willing","determined",
    "unwilling","reluctant",
    "rational","logical",
    "obedient",
    "caring","healing",
    "dynamic","changeable","mercurial","unpredictable",
    "weak","craven","fearful",
    "opinionated","cranky","resolute",
    "educating","guiding","helpful",
    "mystical","mysterious",
    "expositional","revealing",
    "confusing","egocentric","misleading","clever","manipulative",
    "thoughtless","silly","amusing",
    "innocent","naive","simple","straightforward","credulous","endearing",
    "reflecting",
    "quiet","secretive",
    "curious",
    "dedicated","driven",
    "fair","unbiased","patient",
    "thorough","crafty",
    "final","morbid","dark",
    "giving","generous","charitable","patronizing",
    "incredible",
    "wishful","ambitious",
    "dominating","demanding","angry","egocentric","dedicated",
    "alluring","deceitful"

  ],
  "clothingadj": [
    "torn", 
    "well-made",
    "luxurious",
    "simple",
    "ornarte",
    "elegant", 
    "linen", 
    "hemp", 
    "wool", 
    "silk",
    "fur",
    "brocade",
    "cotton",
    "quilted",
    "felt",
    "camel's hair",
    "lambskin",
    "velvet",
    "leather",
    "satin",
    "cashmere",
    "cloth",
    "gauze",
    "hemp",
    "khādī",
    "muslin"

  ],
  "heTorsoClothing": [
    "shirt",
    "doublet",
    "robe",
    "cioppa",
    "hanfu pao",
    "shenyi",
    "jeliqa",
    "vest",
    "waistcoat",
    "jobba",
    "kaftan",
    "kel'at",
    "coat",
    "jacket",
    "pustin",
    "reda",
    "arakqloq",
    "qamis",
    "xuandan",
    "yuanlingshan",
    "lanshan"
  ],
  "sheTorsoClothing": [
    "blouse",
    "gown",
    "long gown",
    "chemise",
    "cotehardie",
    "houppelande",
    "overgown",
    "hanfu qun",
    "pien fu",
    "sheni",
    "cador"
  ],
  "theyTorsoClothing": [
    "#heTorsoClothing#",
    "#sheTorsoClothing#"
  ],

//Given names here
  //Taken from http://heraldry.sca.org/names/arabic-naming2.htm
  "arabicMaleName":[
    "Aban",
    "Abbad",
    "‘Abd al-Rahman",
    "‘Abd Allah",
    "‘Abd al-Aziz",
    "‘Abd al-Hamid",
    "‘Abd al-Malik",
    "‘Abd al-Zahir",
    "‘Abdus",
    "Ahmad",
    "‘Ali",
    "‘Allan",
    "‘Alqamah",
    "‘Ammar",
    "‘Amr",
    "Anas",
    "‘Aqil",
    "‘Arubah",
    "‘Asim",
    "‘Ata’",
    "Ayyub",
    "Babak",
    "Bakkar",
    "Bakr",
    "Bashshar",
    "Baybars",
    "Bilal",
    "Bishr",
    "Bundar",
    "Da’ud",
    "Dabbah",
    "Daffafah",
    "Dahhak",
    "Damdam",
    "Dirar",
    "Durayd",
    "Fadl",
    "Farras",
    "Fudayl",
    "Ghalib",
    "Ghassan",
    "Habib",
    "Hakam",
    "Hakim",
    "Hamdan",
    "Hamdun",
    "Hamid",
    "Hammad",
    "Hamzah",
    "Harb",
    "Harthamah",
    "Harun",
    "Hasan",
    "Hashim",
    "Hassan",
    "Hilal",
    "Hisham",
    "Hujr",
    "Humayd",
    "Hunayn",
    "Husayn",
    "Ibrahim ",
    "Idris",
    "‘Imran",
    "‘Isa ",
    "Ishaq",
    "Isma’il",
    "Iyas",
    "Jabir",
    "Ja’far",
    "Jahm",
    "Jibril",
    "Kamil",
    "Khalaf",
    "Khalid",
    "Khalil",
    "Khattab",
    "Khuzaymah",
    "Labid",
    "Lu’lu’",
    "Ma’bad",
    "Mahmud",
    "Malik",
    "Ma’n",
    "Mansur",
    "Ma’qil",
    "Marwan",
    "Maslamah",
    "Maymun",
    "Mikha’il",
    "Mishal",
    "Mu’adh",
    "Mu’ammar",
    "Mu’awiyah",
    "Mughirah",
    "Muhammad",
    "Mujahid",
    "Munqidh",
    "Muqatil",
    "Musa",
    "Muslim",
    "Muzahim",
    "Nafi’",
    "Najdah",
    "Nasr",
    "Nuh",
    "Nusayr",
    "Qatadah",
    "Qays",
    "Qudamah",
    "Qurrah",
    "Qutaybah",
    "Rabi’a",
    "Rafi’",
    "Ramadan",
    "Rashid",
    "Rawh",
    "Razin",
    "Ru’bah",
    "Sabur",
    "Sa’d",
    "Sa’dan	Sadaqah",
    "Sa’id",
    "Safwan",
    "Sahl",
    "Salamah",
    "Salih",
    "Salim",
    "Salm",
    "Sandi",
    "Sawwar",
    "Sayf",
    "Shabib",
    "Shahib",
    "Shahid",
    "Shahin",
    "Shaybah",
    "Shihab",
    "Shu’ayb",
    "Shuqayr",
    "Sinan",
    "Sufyan",
    "Sulaym",
    "Sulayman",
    "Surayj",
    "Tahir",
    "Talhah",
    "Talib",
    "Tamman",
    "Tawbah",
    "Tha’lab",
    "Thabit",
    "Thawabah",
    "Thawr",
    "‘Ubayd",
    "‘Ubayd Allah",
    "‘Umar",
    "‘Umarah",
    "Umayyah",
    "‘Unaynah",
    "‘Uqbah",
    "‘Urwah",
    "Usama ",
    "‘Utbah",
    "‘Uthman",
    "Wada’",
    "Wahb",
    "Wasil",
    "Ya’qub",
    "Yahya",
    "Yamin",
    "Yazid",
    "Yuhanna",
    "Yunus",
    "Yusuf",
    "Zakariya’",
    "Zayd",
    "Ziyad",
    "Zubayr",
    "Zuhayr"
  ],
  "arabicFemaleName":[
    "Abbasah",
    "Abdah",
    "`Abla",
    "`Afra",
    "`A`isha",
    "Amimah",
    "Aminah",
    "‘Amra",
    "Arwa",
    "Asiya",
    "Asma'",
    "`Atikah",
    "Azizah",
    "`Azzah",
    "Banah",
    "Banujah",
    "Baraka",
    "Bilqis",
    "Buran",
    "Bushra",
    "Buthaynah",
    "Chiklah",
    "Dahah",
    "Dananir",
    "Duqaq",
    "Durra",
    "Fadl",
    "Fatimah",
    "Fawz",
    "Fazila",
    "Ghadir",
    "Ghaniyah",
    "Ghaythah",
    "Hababah",
    "Hafsah",
    "Hakeema",
    "Hala",
    "Halima",
    "Hamama",
    "Hasanah",
    "Hawwa",
    "Hind",
    "Hullah Huma'i",
    "Husn",
    "`Ijliyah",
    "`Ilm",
    "`Inan",
    "Itimad",
    "‘Izza",
    "Jaida",
    "Jamila",
    "Jumana",
    "Juml",
    "Juwayriyyah",
    "Kasif",
    "Khadijah",
    "Khadija",
    "Khaizuran",
    "Khalida",
    "Khayra",
    "Layla",
    "Laila",
    "Lubaba",
    "Lubna",
    "Labna",
    "Mahabba",
    "Malak",
    "Manhalah",
    "Marajil",
    "Maridah",
    "Mariyah",
    "Maryam",
    "Mariam",
    "Maymuna",
    "Maynmunah",
    "Maimuna",
    "Maimunah",
    "Maysun",
    "Mayy",
    "Muhayya",
    "Munisa",
    "Munya",
    "Muti’a",
    "Nafisa",
    "Naila",
    "Nalkah",
    "Nu'm",
    "Nusayba",
    "Nuwwar",
    "Qabul",
    "Qaribah",
    "Rabab",
    "Rabi'ah",
    "Rabia",
    "Rahil",
    "Rahmat",
    "Ramlah",
    "Rayhana",
    "Raym",
    "Rayya",
    "Rudaba",
    "Raziya",
    "Ruqayyah",
    "Ruqayya",
    "Rusa",
    "Rusha",
    "Sabiha",
    "Saduf",
    "Safiya",
    "Safia",
    "Safwah",
    "Saham",
    "Sahla",
    "Sajah",
    "Sakan",
    "Salamah",
    "Salama",
    "Salma",
    "Salmaa",
    "Salsal",
    "Sanaa",
    "Sara",
    "Sawda",
    "Shaima",
    "Shifa",
    "Shiklah",
    "Su'ad",
    "Suad",
    "Subh",
    "Sumayya",
    "Sumnah",
    "Thana'",
    "`Ulayyah",
    "Ulaiyah",
    "Umamah",
    "Umayma",
    "`Utbah",
    "Wahshiyah",
    "Wallada",
    "Warwar",
    "Zaynab",
    "Zainab",
    "Zebeebah",
    "Zabibah",
    "Zubaydah",
    "Zubaida",
    "Zubaidah",
    "Zulaikha"
  ],

  //Taken from http://heraldry.sca.org/names/mongolian_names_marta.html
  "mongolianName": [
    "Abaka",
    "Abaqa",
    "Achigh Shirun",
    "Adarkidai",
    "Adkiragh",
    "Adya",
    "Agasiletai ",
    "Agsaldai ",
    "Aguchu",
    "Agujam ",
    "Achujim",
    "Achujam Bugural",
    "Ajai",
    "Ajinai",
    "Ajir ",
    "Ajirai",
    "Akhutai",
    "Alagh",
    "Alagh Yid",
    "Alchidai ",
    "Alchi",
    "Elchi",
    "Alchigh",
    "Aljai Temur ",
    "Alghu",
    "Altan",
    "Altun Ashugh",
    "Amal",
    "Amasandji",
    "Amasar",
    "Ambaghai",
    "Anarba",
    "Aragibal",
    "Arasen",
    "Argasar",
    "Arabuccha",
    "Argat",
    "Argun",
    "Arin Tasai",
    "Arik",
    "Arik Boge",
    "Ariq Boke",
    "Arik Buka",
    "Ariunbold",
    "Arsi",
    "Aruktai",
    "Argasun Qorchi",
    "Arkhai Khasar",
    "Arslan",
    "Aruch",
    "Asha Gambu",
    "Ashigh Temur",
    "Asugbal",
    "Badai",
    "Bagaridai",
    "Bai Shingor",
    "Baidar",
    "Baidu",
    "Baiju",
    "Bala",
    "Balagachi",
    "Baltu",
    "Bardam",
    "Bartan",
    "Bartu",
    "Barulatai",
    "Baasan",
    "Baavgai",
    "Batachikhan",
    "Bati",
    "Batu",
    "Bayan",
    "Bayan Cagan Tengri",
    "Bayan Olgei",
    "Bayar",
    "Bede",
    "Bedes",
    "Begter",
    "Begugtei",
    "Belgeltei",
    "Belgunutei",
    "Berke",
    "Besutei",
    "Biger",
    "Bilge",
    "Bilig",
    "Boal",
    "Bodonchar",
    "Bogarji",
    "Boge",
    "Esen Boge",
    "Arik Boge",
    "Bogen",
    "Boshigt",
    "Bogorchu",
    "Bolkhadar",
    "Bor",
    "Bora",
    "Borjigidai",
    "Boroghul",
    "Borachu",
    "Boroldai",
    "Boroldai Suyalbi",
    "Bortachikhan",
    "Borte Chinua",
    "Bortei",
    "Bucharan",
    "Bughu Khatagi",
    "Bughutu Salji",
    "Bugidai",
    "Bugunutei",
    "Bugurul",
    "Bujeg",
    "Bujir",
    "Bukha",
    "Arik Buka",
    "Ked-Buqa",
    "Qoribucha",
    "Bukidai",
    "Bulaqadar",
    "Bultechu",
    "Bultger",
    "Bulugan",
    "Buqatai",
    "Buri",
    "Buri Bulchiru",
    "Burim",
    "Burkhan Khaldun",
    "Butu",
    "Buyant",
    "Buyantu",
    "Buyirugh",
    "Carbon",
    "Cyriacus Buyirugh",
    "Chanai",
    "Chanar",
    "Chagadai",
    "Chaghagan",
    "Cagan Ebugen",
    "Chaghagan Khoga",
    "Chaghagan Uua",
    "Chagurkhai",
    "Chakhurkhan",
    "Chapar",
    "Charakha",
    "Chidukhul",
    "Chigu",
    "Chilagun",
    "Chiledu",
    "Chilger",
    "Chiluku",
    "Chimbai",
    "Chimbai Dargan",
    "Chingay",
    "Chingkim",
    "Choban",
    "Chormakhan",
    "Chulgetei",
    "Chuacenur",
    "Dagun",
    "Daidukul",
    "Dalantai",
    "Darbai",
    "Daritai",
    "Dash",
    "Dayan",
    "Dayir",
    "Dayir Usun",
    "Degei",
    "Dei",
    "Delbeg",
    "Delger",
    "Devet Berdi",
    "Dhunan",
    "Dinget",
    "Dobun",
    "Dodai",
    "Dogar",
    "Dogshin",
    "Dokholkhu",
    "Dologadai",
    "Donoi",
    "Dorbei",
    "Dori Bukha",
    "Durulji Tayiji",
    "Duua",
    "Edigu",
    "Eguden Yeke",
    "Elbek",
    "Eldegai",
    "Eljigidei",
    "Emlig",
    "Enx",
    "Erdeni",
    "Erke",
    "Erke Khara",
    "Erketu",
    "Esen Boge",
    "Esen Taij",
    "Esen Taysh",
    "Esugen",
    "Gal",
    "Galdan",
    "Caikhatu",
    "Gerel",
    "Geser",
    "Geser Khan",
    "Geugi",
    "Ghazan",
    "Ghunan",
    "Guchlug ",
    "Guchu",
    "Guchugur",
    "Gughlug",
    "Gugun",
    "Guntomor",
    "Gur",
    "Guyug",
    "Harghasun",
    "Hobogetur",
    "Hooshal",
    "Horkhudagh",
    "Hulegu",
    "Huslen",
    "Huslen Hutagt",
    "Husun",
    "Hychyt",
    "Idughadai",
    "Ile",
    "Ilugei",
    "Inalchi",
    "Inancha Bilge",
    "Iturgen",
    "Jakha Gambu",
    "Jaghatai",
    "Jajiradai",
    "Jali Bukha",
    "Jamugha",
    "Janggi",
    "Jarchigudai",
    "Jebe",
    "Jebein Noyan",
    "Jeder",
    "Jelme",
    "Jenkshi",
    "Jirandai",
    "Jirghadai",
    "Jirghogadai",
    "Jebke",
    "Jegu",
    "Jelme",
    "Jetei",
    "Jochi",
    "Jochi Khasar",
    "Jubkhan",
    "Jungdu",
    "Jungsai",
    "Jungso",
    "Jungshoi",
    "Jurchedei",
    "Kamala",
    "Kara",
    "Kara Hekegu",
    "Kepek",
    "Ketboge",
    "Kete",
    "Keuken",
    "Khabichi",
    "Khabul",
    "Khachi",
    "Khada",
    "Khadagan",
    "Khadagan Daldurkhan",
    "Khadagan Tasai",
    "Khadagh",
    "Khadan",
    "Khagatai Darmala ",
    "Khaguran",
    "Khaidai",
    "Khaidu",
    "Khaishan",
    "Khaji Kulug ",
    "Khajigin",
    "Khal",
    "Khali Kharchu",
    "Khaligudar",
    "Khalja",
    "Khara Gulug",
    "Qara Budang",
    "Kharachar",
    "Kharchu",
    "Khasar",
    "Khashi ",
    "Khashin",
    "Khongkhai",
    "Khongtaghar",
    "Khorichar",
    "Qoricar Mergan",
    "Khorchi",
    "Khorghosun",
    "Khori Shilemun Taisi",
    "Khori Subechi",
    "Khoridai",
    "Khorilartai",
    "Khongkhortai",
    "Khubilai",
    "Khuchar",
    "Khudu",
    "Khudus",
    "Khudus Khalkhan",
    "Khudukha",
    "Khulan",
    "Khurchakhus",
    "Khuril Ashigh",
    "Khutughtu",
    "Khutula",
    "Khuyildar",
    "Kinggiyadai Bukha",
    "Kiratai",
    "Kiriltugh",
    "Kishiligh",
    "Kogsegu Sabragh",
    "Kekchu",
    "Koko",
    "Koko Chos",
    "Koko Mongke",
    "Kokochu",
    "Kokochu Kirsagan",
    "Kokochu Teb Tenggeri",
    "Kopek",
    "Kotyan",
    "Kuchar",
    "Kundek",
    "Kus Bulad",
    "Kutlugh",
    "Temur Kutlugh",
    "Kuyuk ",
    "Kuzhuk",
    "Labakha ",
    "Ligdan",
    "Luvsan",
    "Magnai",
    "Mahamu",
    "Maqa Tudan",
    "Maqali",
    "Maral",
    "Masgud",
    "Mauci",
    "Megujin",
    "Menggei",
    "Menggetu",
    "Menggulig",
    "Megetu",
    "Molon",
    "Mengu",
    "Mergen",
    "Mongke",
    "Mongke Temur",
    "Monke Temur",
    "Tode Mongke",
    "Tuda Mongke",
    "Yesu Mongke",
    "Monx",
    "Morokha",
    "Mungke",
    "Muge",
    "Mukhali",
    "Mulkhalkhu",
    "Munglig",
    "Mungetu",
    "Munggugur",
    "Munokhoi",
    "Mutugen",
    "Myagmar",
    "Nachin",
    "Nakhu",
    "Narin",
    "Narin Kegen",
    "Narin Togoril",
    "Nayaga",
    "Nayan",
    "Nayantai",
    "Jebei Noyan",
    "Nekun",
    "Nekun Taisi",
    "Nogai",
    "Nongrot",
    "Odchigin",
    "Odchigin Abaga",
    "Temuge Otchigin",
    "Ogele",
    "Ogodei",
    "Okhotur",
    "Okin",
    "Okin Barkhagh",
    "Olai Anda",
    "Olar",
    "Oldaghar",
    "Ozbeg",
    "Olzii",
    "Olziytomor",
    "Oljeitu",
    "Ong",
    "Onggiran",
    "Onggur",
    "Orda",
    "Ordu Coronartai",
    "Osol",
    "Oyuun",
    "Ozbeg",
    "Qobolta",
    "Qoribuqa",
    "Qorisubechi",
    "Qoriqacha",
    "Sacha",
    "Sagra",
    "Sain",
    "Sanchir",
    "Sartak",
    "Sechegur",
    "Seger Sandalitu",
    "Semsochi",
    "Senggum",
    "Sidurgu",
    "Shager",
    "Shigi Khutukhu ",
    "Shiban",
    "Shigi-Qutuqu",
    "Shikigur",
    "Shilugei",
    "Shinghkhor",
    "Shiraghul",
    "Shiramun",
    "Shirgugetu",
    "Sibaguchu",
    "Siban",
    "Sinkur",
    "Sokhor",
    "Sorkhan Shira",
    "Sorkhatu Jurki",
    "Soyiketu",
    "Subetei",
    "Sugar",
    "Suke",
    "Sukhebaatar",
    "Sukegei",
    "Suyiketu",
    "Tabudai",
    "Tabur",
    "Tagadhur",
    "Taghai",
    "Tahar",
    "Taichar",
    "Taichu",
    "Tamachi",
    "Tamachag",
    "Taragai",
    "Tarmashirin",
    "Tartu",
    "Tatar",
    "Tatatunga",
    "Tayang",
    "Teb Tengri",
    "Tekuder",
    "Teguder Ahmad",
    "Teleboge",
    "Telegetu",
    "Temuge",
    "Temuge Otichigin",
    "Temujin",
    "Temujin Uge",
    "Temur",
    "Aljai Temur",
    "Ashigh Temur",
    "Durra Timur",
    "Timur Molie",
    "Tokur Temur",
    "Togha Timur",
    "Temur Kutlugh",
    "Temur Oljeitu",
    "Toghon Temur",
    "Bash Timur",
    "Mongke Temur",
    "Thaube",
    "Tobsakha",
    "Tobukha",
    "Todogen Girte",
    "Togh",
    "Togh Temur",
    "Toq Temur",
    "Togos Temur",
    "Toghon",
    "Toghon Temur",
    "Toghoril",
    "Toghtoga",
    "Togtoobuh",
    "Tokhuchar",
    "Tokhta",
    "Tokhtamysh",
    "Tole-Buqa",
    "Tolon",
    "Tolui",
    "Tolun",
    "Tomor Olziyt",
    "Torbi Tashi",
    "Tordung",
    "Torgan Sira",
    "Torgaljin",
    "Torgan",
    "Tseren",
    "Tsolmon",
    "Tuda Mongke",
    "Tudan",
    "Tugan",
    "Tuge",
    "Tumbinai",
    "Tumun",
    "Tungge",
    "Tungkhuidai",
    "Tutei",
    "Tuva",
    "Yesun Tuva",
    "Tuyuideger",
    "Uchikin",
    "Udutai",
    "Uighurtai",
    "Ukhuna",
    "Ukilen",
    "Ulagchi",
    "Uran Cenggui",
    "Urchger",
    "Urgamal",
    "Urus",
    "Uriangkadai",
    "Usun",
    "Xangai",
    "Xartsaga",
    "Xorxoi",
    "Yabuqa",
    "Yalavech",
    "Yargai",
    "Yasavur",
    "Yedi Tublugh",
    "Yegu",
    "Yerentai",
    "Yesugei",
    "Yesunge",
    "Yeke",
    "Yeke Cheren",
    "Yeke Chiledu",
    "Yeke Couru",
    "Yeke Nidun",
    "Yeki Negurin",
    "Yesu Mongke",
    "Yesun",
    "Yesun Tege",
    "Yesun Temur",
    "Yesun Tuva",
    "Yokhunan",
    "Yurukhan",
    "Zayaat",
    "Zhims"
  ],


//Taken from https://www.s-gabriel.org/names/ursula/tamil/
  "indianMaleName": [
    "Nirupatonkavarman",
    "Virajakecaripanmar",
    "Parakesaipanmar",
    "Uttamacola",
    "Rajarajakesaripanmar",
    "Arattan Ikatutevan",
    "Accan Pattalkan"
  ],
//Taken from https://sites.google.com/site/vairavisca/Home/creations/indian-name-research
  "indianFemaleName":[
    "Ammāti Naṅkaic Cāni",
    "Aṟam Uṭaiyāḷ",
    "Ariya Piḷḷai",
    "Arumoḻi Naṅkaiyār",
    "Cāmuṇṭappai",
    "Cavariy",
    "Ciṇṇavaiyār",
    "Cōmāci Cāṇi",
    "Iḷaiya Maṇi Naṅkai",
    "Kaṉaka Vīrak Kurattiyār",
    "Kaṅkaṉaic Cāṉi",
    "Kaṇṇa Pirāṭṭiy",
    "Kōmaḷa Valli",
    "Kumaraṭi Naṅkai",
    "Maṅkaiyarkaraciyār",
    "Maṅkaiyarkaraici",
    "Maṅkaiyarkkaraciyār",
    "Maturāntakiyār",
    "Miṭṭāṇṭār Nācciyār",
    "Mūtta Naṅkaiyār",
    "Nācci",
    "Nantiri Naṅkai",
    "Nilammai",
    "Paṭṭiṉik Kuratti Aṭikaḷ",
    "Peṅki",
    "Peṇṇaraciyār",
    "Tavañ Ceytāḷ",
    "Tēmpāvai",
    "Tēvāṉṟāḷ",
    "Tēvi",
    "Tiruvampalam Piriyāta Piḷḷaiyāṉ",
    "Toṇṭaimā Nācciyār",
    "Toṇṭaimā Nācciyār",
    "Umaiyāḻvār",
    "Umaiyāḻvār",
    "Utaiyañceytāḷ",
    "Vaccavaiyār",
    "Vampu",
    "Vampu Paḻuttāḷ",
    "Vaṭavāyil Aṇṭai",
    "Veṇṇāyi Naṅkai"


  ],

//Taken from http://www.peiraeuspubliclibrary.com/names/medievalnames/medievalchina.html
  "chineseMaleName":[
    "Ao",
    "Bang",
    "Buwei",
    "Changdong",
    "Chao",
    "Chai",
    "Fuling",
    "Gao",
    "Guang",
    "Han",
    "He",
    "Hu Hai",
    "Jizi",
    "Ju",
    "Kang",
    "Long",
    "Lun",
    "Mang",
    "Qi",
    "Qian",
    "Qing",
    "She",
    "Sheng",
    "Shi",
    "Si",
    "Taizong",
    "Tian",
    "Wan",
    "Xian",
    "Xie",
    "Xin",
    "Xing",
    "Yang",
    "Yide",
    "Ying",
    "Yu",
    "Yuan",
    "Yun",
    "Zang",
    "Zhanghaui",
    "Zhao",
    "Zheng",
    "Zhou",
    "Ziying"
  ],

  "chineseFemaleName":[
    "Feiyan",
    "Hou",
    "Ji",
    "Jiangnu",
    "Lihau",
    "Na",
    "Shengtong",
    "Zhi"
  ],
  "byzantineFemaleName":[
    "Agatha",
    "Anastasia",
    "Anna",
    "Antonia",
    "Ariadne",
    "Athenais",
    "Constantina",
    "Epiphania",
    "Eudokia",
    "Eulogia",
    "Euphrosyne",
    "Helena",
    "Irene",
    "Joannina",
    "Maria",
    "Martina",
    "Sophia",
    "Thekla",
    "Theodora",
    "Theophano",
    "Yolanda",
    "Zoe"
  ],
  "byzantineMaleName":[
    "Alexander",
    "Alexios",
    "Anastasius",
    "Andronikos",
    "Antigonos",
    "Antonius",
    "Antony",
    "Arcadius",
    "Arethas",
    "Asylaion",
    "Basil",
    "Basiliscus",
    "Basiliskianos",
    "Belisarius",
    "Callinicus",
    "Christopher",
    "Constantine",
    "Constantius",
    "Damianus",
    "David",
    "Demetrios",
    "Diocletian",
    "Eutathios",
    "Euthymius",
    "George",
    "Heraclius",
    "Heraclonas",
    "Himerius",
    "Ignatios",
    "Isaac",
    "John",
    "Julian",
    "Justinian",
    "Leo",
    "Leontius",
    "Licinius",
    "Manuel",
    "Michael",
    "Mousoulios",
    "Nicholas",
    "Nikephoros",
    "Niketas",
    "Petronas",
    "Philippicus",
    "Philaretos",
    "Phocas",
    "Photios",
    "Romanus",
    "Stauracius",
    "Stylian",
    "Theodore",
    "Theodosios",
    "Theoktistos",
    "Theophilus",
    "Valens"
  ],
//From sources from https://s-gabriel.org/names/islamic.shtml

  "persianFemaleName": [
    "Bakht",
    "Bakht Dawlat",
    "Bakht Nigâr",
    "Dawlat",
    "Dawlat Bakht",
    "Dil",
    "Dil Dâr",
    "Dil Khûsh",
    "Dil Shâd",
    "Durr",
    "Fâkhire",
    "Firuz Bakht",
    "Firuze",
    "Gawhar",
    "Gawhar Shâd",
    "Gul",
    "Gul Badan",
    "Gul Bîkî",
    "Gul Nâr",
    "Gul Rang",
    "Gul Rukh",
    "Gul Shâd",
    "Husn Nigâr",
    "Jân",
    "La'l",
    "Mihr Bânû",
    "Mihr Khush",
    "Mihr Nigâr",
    "Nâr Gul",
    "Nigâr",
    "Nurûz",
    "Pîrûz",
    "Shâd Bakht",
    "Shâd Bânû",
    "Shahr Bânû",
    "Shîrîn"
  ],
  "persianMaleName": [
      "`Abd al-Khâliq",
      "`Abdullâh",
      "Abû Nasr",
      "`Alî",
      "`Ârif",
      "Hasan",
      "Khalîl",
      "Kulâl",
      "Mahmûd",
      "Muhammad",
      "Qutham",
      "`Ubaydullâh",
      "Ya`qûb",
      "Yûsuf"
    ],
  //List of family names below

  "chineseFamilyName":[
    "Ban",
    "Chang",
    "Chen",
    "Chu",
    "Dong",
    "Dou",
    "Fa",
    "Gou",
    "Huo",
    "Jian",
    "Li",
    "Liang",
    "Liu",
    "Lu",
    "Ma",
    "Meng",
    "Shang",
    "Xuan",
    "Wang",
    "Wei",
    "Wu",
    "Xiang",
    "Yin",
    "Zhao",
    "Zhuang",
    "Zuan"
  ],
  
  "persianFamilyName":[
    "Ahrâr",
    "Anjîr Faghnawî",
    "Attar",
    "Charkhî",
    "Ghujdawânî",
    "Hamadânî",
    "Isfahânî",
    "Kâshgharî",
    "Khâmûsh",
    "Naqshband",
    "Pârsâ",
    "Rîwgirawî",
    "Samâsiyî"
  ],
  "byzantineFamilyName":[
    "Bringas",
    "Choniates",
    "Comnenus",
    "Cydones",
    "Dalassema",
    "Ducas",
    "Lascaris",
    "Maleinos",
    "Maniaces",
    "Phokas",
    "Prodromus",
    "Psellos",
    "Scylitzes",
    "Tzimiskes",
    "Xiphilinos"
  ],

  "indianFamilyName":[
    ""
  ]
}

let things_desc = {
  "findThing":[
    "[setArtifact:#artifact#]The #artifact# was #description#, and was #power#.",
    "#idiom# The #mat1# #artifact# #madeWith# #mat2# was #there# on #altar.a#.",
    "#idiom# As I #moved# #silently# inwards, I #saw# the #mat1# #artifact# #madeWith# #mat2# on the #altar#."
    ],

    "moved":[
      "crept",
      "crawled",
      "snuck",
      "walked"
    ],

    "silently":[
      "quietly",
      "silently",
      "noiselessly",
      "calmly",
      "soundlessly"
    ],

    /* "location":[
      "placeholder, variable drawn from other grammar?"
    ], */

    "saw": [
      "discovered",
      "found",
      "saw",
      "noticed",
      "uncovered",
    ],

    "power":[
     "gleaming with inner light",
     "light as a feather",
     "untouched by dust or wear",
    ],

    "idiom":[
      "Thank goodness!",
      "Praise the heavens!",
      "Lucky little me!",
      "Fortune smiles upon me!",
      "-haha, I've still got it!"

    ],

    "madeWith":[
      "inlaid with",
      "constructed with",
      "detailed with"
    ],

    "artifact":[
      "book",
      "tome",
      "knife",
      "sash",
      "mask",
      "arrow",
      "pouch",
      "spike",
      "brush",
      "sword",
      "bag",
      "bell",
      "belt",
      "mirror",
      "bones",
      "seed",
      "comb",
      "boot",
      "bracer",
      "cage",
      "candelabrum",
      "cauldron",
      "chair",
      "throne",
      "charm",
      "chime",
      "collar",
      "compass",
      "crown",
      "cruicble",
      "crystal",
      "root",
      "badge",
      "mantle",
      "drum",
      "torc",
      "ring",
      "bracelet",
      "ring",
      "girdle",
      "glove",
      "amulet",
      "hilt",
      "trinket",
      "prayer strip",
      "skull",
      "needle",
      "cup",
      "map",
      "doll",
      "sheathe",
      "pip",
      "dagger",
      "scroll",
      "scepter",
      "quill",
      "stamp",
      "pen",
      "pin",
      "talisman",
      "urn",
      "vessel"
    ],

    "description":[
      "made of #mat1# and #mat2#",
      "made of #mat1# with #mat2.a# inlay",
      "constructed with #mat1# and bits of #mat2#",
      "etched with #mat1# and coated in #mat2#",
      "spiked with #mat2# on a base of #mat1#"
    ],

    "mat1": [
      "jade",
      "wood",
      "ivory",
      "ebony",
      "iron",
      "brass",
      "gold",
      "bamboo",
      "bone",
      "glass",
      "silver",
      "bronze",
      "reeds",
      "cotton",
      "linen"
    ],

    "mat2":[
      "jade",
      "wood",
      "ivory",
      "ebony",
      "iron",
      "brass",
      "gold",
      "bamboo",
      "bone",
      "glass",
      "silver",
      "bronze",
      "reeds",
      "cotton",
      "linen"
    ],

    "detail":[
      "in a floral pattern",
      "in an animal pattern",
      "in a spiral design",
      "in a circular design",
      "in a blocky pattern",
      "smudged with grease",
      "covered in dust",
      "with many small dents",
      "with a crack through the center",
      "with one side chipped",
      "with visible wear",
      "with unsightly stains",
      "with slight mold growth",
      "with some water damage",
      "with a name inscribed on it",
      "with a sigil branded on it",
      "that was slightly too big",
      "that was slightly too small",
      "just the right size",
      "brand new",
      "carefully cleaned",
      "recently repaired",
      "emiting a strange odor",
      "emiting a pleasent scent",
      "ringing slightly",
      "colored darker",
      "colored lighter"
    ],

    "there":[
      "left alone",
      "dropped carelessly",
      "sitting",
      "lying against",
      "drapped over",
      "carefully set"
    ],

    "altar":[
      "altar",
      "podieum",
      "table",
      "stand",
      "pillar",
      "base",
      "chair",
      "surface"
    ]

}

// @notkrd (forked from landscape_desc.json)
let landscape_desc = {
  "origin":["[theCrop:#crop#]#fields#","#terrain#"],
  
  "fields":["#fields_morning#","#fields_night#", "Fields of #crop# #expanse#, towards the horizon."],
  "fields_morning":["[theTime:morning]#weather_time#. #inhabited_desc#"],
  "fields_night":["[theTime:night]#weather_time#. #uninhabited_desc#"],
  "crop":["barley","rice","wheat","cotton","peas","lentils","onions"],
  "inhabited_desc":["#farmers.capitalize# #moved_through# fields of #theCrop#."],
  "uninhabited_desc":["Fields of #theCrop# #expanse#, #uninhabited_prep#.", "#animal.capitalize# flitted through the #uninhabited# fields."],
  "uninhabited_prep":["now #uninhabited#", "with no soul in them"],
  "farmers":["#farmer_desc# #farmer_bodies#","#lines_of# #farmer_bodies# carrying #tool#"],
  "farmer_desc":["hunched", "#lines_of#"],
  "farmer_bodies":["bodies","souls","farmers"],
  "tool":["sacks","hoes"],
  
  "terrain":["#steppes#"],
  
  "steppes":["The steppes #expanse# around us travelers."],
  
  "uninhabited":["vacant","empty"],
  "lines_of":["lines of", "rows of", "many"],
  "animal":["crows", "hamsters"],
  "moved_through":["moved through", "walked across", "labored in"],
  "weather_time":["It was a #weather# #theTime#"],
  "weather":["crisp", "sodden", "warm", "dry"],
  "expanse":["stretched out", "expanded", "covered the earth"]
}

// @jazztap
let event_stubs = {
    'need': [],
    'find': { ...things_desc,
              'origin': 'I found #3# at #2#. #findThing#.'},
    'reflect': ['I thought about #2# in the safety of #1#. I held #3# in my hands.'],
    'unleash': ['#3# once warned me of courting #2#, whose haunt was #1#. But it was too late.'],
    'murder': ['In the streets of #2#, I shot #1# with an arrow through the breastbone.'],
    'seethe': { ...things_desc,
                'origin': 'I had met #1# in #2#, where they sold me a useless #3#, #artifact.a# #detail#.'},

    'relax': ['I went on a walk with #1#, while we considered the matter of #2#.'],
    'contact': ['#1# introduced me to #2#.'],
    'speechify': ['I regaled the people of #1#. Afterward, #2# sought me out.'],
    'unhappiness': ['The streets of #1# seemed vacant. #2# spoke to me lowly.'],
    'happiness': ['The streets of #1# were brimming with celebrants, #2# sometimes joining them.'],
    'mill-around': {...things_desc,
                    'origin': 'I explored #1#, finding #2# for sale from local vendors: #artifact.a# #madeWith# #mat2# #detail#.'},

    'find-friend': ['While in #2#, I met #1# by chance.'],
    'save-friend': ['I discovered #1# was menaced by #2#.'],
    'save-town': ['I resolved to stay in #1#. #2# soon moved against it, but we were ready.'],
    'travel-forced': ['I could no longer stay in #1#. Remembering #2#, I left for #3# to seek it out.'],

    'travel-quest': ['I journeyed to #2# following #1#.'],
    'learn': ['I found out about #1#.'],
    'learn-at': ['I found out #1# is at #2#.'],
    'make': [],
    'master': [],
    'intend-gift': ['I wanted to give #1# a birthday gift.'],
    'intend-hurt': [],
    'intend-impress': [],
    'intend-help': [],

    'gift': ['I gave #2# to #1#.'], // 'I gave the {} to {}.']
    'journey-end': ['I concluded my journey.'],
    'journey-event': {...landscape_desc,
                      'origin': ['I encountered a bizarre creature.',
                                 'I trekked an incredible vista. #terrain#',
                                 'I approached a town. [theCrop:#crop#]#fields#']},
    'journey-start': ['I set out again.'],
    'journey-new': ['I strove after my object.'],
    'journey-resolve': ['I passed through.'],
    'macguffin-new': ['I started to look for #1#.'],
    'macguffin-resolve': ['I finished my sub-quest for #1#.'],
    'intro-character': {...appearance, ...desc_clothing,
                        'origin': '#0# began to tell their tale: #myStory#'},
  }

let events = Object.keys(event_stubs)

let eventer = events.reduce((res, k) => {
  let U = event_stubs[k].origin ?
          event_stubs[k] : {"origin": event_stubs[k]}
          // turn stubs into grammars. leave grammars alone.

  res[k] = U
  return res
}, {})