let eventer = {
    'need': [],
    'find': ['{0} found {3} at {2}.'], // me, notion, place, thing
    'reflect': ['{} thought about {}.'],
    'relax': [],
    'travel-forced': [],
    'travel-quest': ['{} journeyed to {2} following {1}.'],
    'learn': ['{} found out {}.'],
    'learn-at': ['{} found out {} is at {}.'],
    'make': [],
    'discover': [],
    'master': [],
    'intend-gift': ['{} wants to give {} a birthday gift.'],
    'intend-hurt': [],
    'intend-impress': [],
    'intend-help': [],
    'gift': ['{} gave {2} to {1}.'], // 'I gave the {} to {}.']
    'journey-end': ['{} concluded their journey.'],
    'journey-event': ['{} encountered something on their journey.'],
    'journey-start': ['{} began their journey.'],
    'journey-new': ['{} began their nested journey.'],
    'journey-resolve': ['{} began their nested journey.'],
    'macguffin-new': ['{} started to look for {}'],
    'macguffin-resolve': ['{} finished their sub-quest for {}'],
    'intro-character': ['Introduce {}'],
  }